language: python

jobs:
  include:
    - stage: Tests
      python: 2.7
      <<: &tests        # Anchor https://blog.daemonl.com/2016/02/yaml.html
        install: pip install -r requirements.txt
        script: python tests.py
    
    # Also test for some other versions
    # <<: is the extend operator = add all fields and extend or modify them afterwards
    # without extend operator only exact copies are possible
    - <<: *tests    # Alias for anchor defined above
      python: 3.4
    - <<: *tests
      python: 3.6
    
    # Just to see if experiments with anchors lead to same results
    - stage: Copy of tests
      name: Python test 3
      install: pip install -r requirements.txt
      script: python tests.py
    - name: Python test 4
      install: pip install -r requirements.txt
      script: python tests.py
