language: python

jobs:
  python:
    - "3.4"
    - "3.6"
  include:
    - stage: Tests
      name: Python test 1
      install: pip install -r requirements.txt
      script:
        - python tests.py
        - python tests.py
      name: Python test 2
      script:
        - python tests.py
        - python tests.py
    - stage: Copy of tests
      name: Python test 3
      install: pip install -r requirements.txt
      script:
        - python tests.py
        - python tests.py
