language: python

jobs:
  include:
    - &tests
      stage: Tests
      python: 3.6
      install: pip install -r requirements.txt
      script: python tests.py
    
    # Also test for some other versions
    - <<: *tests
      python: 3.4
    - <<: *tests
      python: 2.7
      
    - stage: Copy of tests
      name: Python test 3
      install: pip install -r requirements.txt
      script: python tests.py
    - name: Python test 4
      install: pip install -r requirements.txt
      script: python tests.py
