language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
  
cache: pip

install:
  - pip install -r requirements.txt

script: skip

jobs:
  include:
    - stage: Tests
      script: python pytest.py
    - stage: Tests2
      script: python pytest2.py
