language: python

jobs:
  install: pip install -r requirements.txt
  include:
    - stage: Tests
      name: Python test 1
      #install: pip install -r requirements.txt
      script: python tests.py
    - name: Python test 2
      #install: pip install -r requirements.txt
      script: python tests.py
      
    - stage: Copy of tests
      install: pip install -r requirements.txt
    - name: Python test 3
      script: python tests.py
    - name: Python test 4
      script: python tests.py
