language: python

jobs:
  include:
    - &tests
      install: pip install -r requirements.txt
      script: python tests.py
      
    -stage: Tests
      name: Python test 1
      <<: *tests
      python: 3.4
    - name: Python test 2
      <<: *tests
      python: 3.6
      
    - stage: Copy of tests
      name: Python test 3
      install: pip install -r requirements.txt
      script: python tests.py
    - name: Python test 4
      install: pip install -r requirements.txt
      script: python tests.py
